### ISSUE TITLE
readOffset not working properly

### ISSUE THREAD

**Issue by anthonycollini** [thefrontside/ember-impagination#169]
I am trying to set the `readOffset`, so my API returns the correct results. My API is using the Rails Kaminari gem, which returns the same results for page 0 and 1. I am trying to get `ember-pagination` to start at page 1 when fetching results, but the settings don't seem to stick.

What is the proper way to set the `readOffset`, or do I need to change a different parameter?

```
{{#impagination-dataset
   fetch=(action 'fetch')
   on-object-at=(action "onObjectAt")
   on-init=(action 'initializeReadOffset')
   on-observe=(action "logDatasetState")
   page-size=25
   as |records|}}
...
```

```
  setReadOffset: task(function * (dataset, offset) {
    yield timeout(5);
    dataset.setReadOffset(offset);
  }).restartable(),

  actions: {
    initializeReadOffset(dataset) {
      this.get('setReadOffset').perform(dataset, 26);
    }
...
```

**Comment by anthonycollini** [comment]
I got around this by adding + 1 to the pageOffset in my fetch call, but I am still looking for a better solution:


```
  actions: {
    fetch(pageOffset, pageSize, stats) {
      return this.get('store').query('transaction', {
        account_id: this.get('model.id'),
        page: pageOffset + 1
      });
    },
...
```

**Comment by flexyford** [comment]
Hi @anthonycollini

The `pages` interface of [Impagination](https://github.com/flexyford/impagination#load-horizon) is an array-like object, and therefore zero-indexed. We pass the `pageOffset` to the `fetch` function so we can customize our queries.  Your code example above is exactly how you should begin fetching from page 1
