### ISSUE TITLE
Can't load more after 2nd fetch

### ISSUE THREAD

**Issue by queenvictoria** [thefrontside/ember-impagination#213]
Thanks for the work on the addon!

I'm trying to load 3 records at a time from a JSONAPI dataset.
I'm using `ember-route-action-helper` with all the logic in the route (no controller).

Working through the chain of events I can set `setReadOffset` being called through `ember-impagination` all the way to `impagination`. Then I can see `_fetchPages` being called with an `unrequested` array. The first two times (`init` and my first `setReadOffset` via a button) the `unrequested` array has a single object in in. The third time it's empty which means my route action `fetch` isn't called. It doesn't matter whether there are 12 records or 1200 records. The third time (the second `setReadOffset`) it's always empty.

If I don't set `stats.totalPages` the 3rd request also results in nothing.

And if I set `load-horizon` to 6 (twice page size) I get 6 records (instead of the expected 3).

Any thoughts @flexyford ?

Template
```handlebars
  {{#impagination-dataset
      fetch=(route-action 'fetch')
      unfetch=(route-action 'unfetch')
      on-init=(route-action 'initializeReadOffset')
      page-size=3
      load-horizon=3
      as |records|}}
  {{#each records as |record index|}}
     {{ index }} {{ record.content.title }}<br>
  {{/each}}

    <button class="btn" {{action records.setReadOffset records.stats.newOffset }}>Load More</button>

  {{/impagination-dataset}}
```

Route
```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model(params) {
    return this.get('store').findRecord('aspect', params.aspect_id);
  },

  pageSize: 3, 
  loadHorizon: 3,
  readOffset: 0,

  actions: {
    initializeReadOffset: function(dataset) {
      dataset.setReadOffset(this.readOffset);
    },

    fetch: function(pageOffset, pageSize, stats) {
      let params = {
        offset: pageOffset,
        limit: pageSize,
      };
      // fetch a page of records at the pageOffset
      return this.store.query('article', params).then((data) => {
        let meta = data.get('meta');
        stats.totalPages = meta.totalPages;
        stats.newOffset = pageOffset + Math.floor(data.content.length/pageSize);
        return data.toArray();
      });
    },

    unfetch: function(records, pageOffset) {
      this.store.findByIds('record', records.map(r => r.id).then(function(records) {
        records.forEach(record => record.deleteRecord());
      }));
    },
  },

});
```

**Comment by flexyford** [comment]
Hi @queenvictoria, thanks for reaching out. 

I recreated your code in an `ember-twiddle`. I was able to replicate your problem. I think the issue is your `readOffset` may not be updating properly due to this line . . . 

> stats.newOffset = pageOffset + Math.floor(data.content.length/pageSize);

I see you're computing the next `readOffset` in your fetch promise handler, but it might be the same number as your current `readOffset`. If that's the case, clicking the `loadMore` button will ignore the request, since the dataset has already loaded your data for that `readOffset`.

For example, if `stats.newOffset //=> 3` and `dataset.readOffset //=> 3`, clicking `Load More` button will have no effect.

Could you explain that line a little more? If I'm not mistaken, `Math.floor(data.content.length/pageSize) // => 1` since the content length should be exactly one `pageSize`.

Hope you found this helpful. Let me know if this is indeed the issue.

**Comment by queenvictoria** [comment]
Hi @flexyford thanks for the quick response! 

What I found when I `setReadOffset` to `records.length` was that it loaded too many records at once (about . From what I understand `readoffset` is the current page offset (not the current record number). Setting it to `records.length` doesn't seem to be right for two reasons.

1.`{{ records.length }}` seems to be (close) to the entire set of the records not just those loaded (`stats.totalPages` * `limit`).
2. I understood `setReadOffset` to be pageOffset not record offset. IE where we are out of `totalPages`. So I'd've thought that it should be the number of records received divided by the limit (records per page) plus the current offset. Which is what that `Math.floor` line is for. 

But re-examining the request sent out I see that `setReadOffset` is recalculated somewhere and correctly sets `offset` based on `limit`. So I'll redo my maths. And remove setting `stats.totalPages` to see if that then correctly sets `records.length`.

**Comment by queenvictoria** [comment]
Ok! You were quite right. My misunderstanding around readOffset vs pageOffset combined with an underlying API error had me chasing my tail. Apologies for that.

(FYI: The API error was that it wasn't always returning the number of records that were requested. This put the pager out of sync and made it hard to debug.)
