### ISSUE TITLE
Add the ability to reset a dataset programatically

### ISSUE THREAD

**Issue by toddjordan** [thefrontside/ember-impagination#34]
Hi!  I heard the podcast on this and liked the ideas behind it, and at the same time had a component that I needed to add infinite scroll to, so I thought I'd give it a whirl.  I'm on my second day now and I still haven't got this basically working in my app.  Hate create an issue for it but was unsure of what other venue I had. If I stick with this library I'd be happy to PR any shortcomings. 

So here it goes...

1. No clear way to reset the impaginator dataset.  
Since I'm a search component, my dataset changes as the user changes the search query.  Whenever the user changes the search.  I couldn't find a way to reset things at first.  The dataset seems to only be recreated when the pagination parameters change, which I didn't want to do.  I finally settled on just creating the dataset myself and passing it as a component attribute, which meant I also had to pass the dataset state as an attribute (since the dataset has an observer that sets it).  Anyways, that seems to get me farther, but also seems hackish
2. My list is rendering before the promise resolves from fetch
my fetch function is called, in which I make a query call to the ember store and return the resulting promise.  I add a `then` to that promise which sets the `stats.totalPages` and sets the result data on my own component (so that I can fill in decorating information on the UI about results), and I return an array of results
Here's the order I see: 

* `fetch` is called (returning the ember-data query promise)
* list is rendered (with a bunch of undefineds)
* `then` function runs and returns results
* nothing re-rendered

Any guidance around this would be appreciated.  I can post some code as well, but I wanted to make sure my scenario is one that makes sense.

**Comment by toddjordan** [comment]
Also, what scope should fetch be under?  I find myself having to bind it to my own component so I can access component properties (to set information about about the result)

**Comment by toddjordan** [comment]
fetch function: 

```javascript
    fetchChats(pageOffset, pageSize, stats) {
        console.log('fetch');
        return this.get('store').query('chat-search-result', {
            query: this.get('chatSearchResultSuggestion.searchValue'),
            expand: 'to,from',
            targetJids: [this.get('activeRoom.jid')],
            pageSize: pageSize,
            pageNumber: pageOffset,
            order: 'recent'
        }).then((searchResults) => {
            console.log('then');
            const results = searchResults.get('content').mapBy('record');
            this.set('chatSearchResultSuggestion', ResultSuggestion.create({
                results: results,
                metaData: { total: searchResults.get('meta.total') },
                searchValue: this.get('chatSearchValue')
            }));
            stats.totalPages = searchResults.get('meta.total');
            console.log(`results of then`);
            console.dir(results);
            return results;
        });
    },
```

Code that creates a dataset to refresh on new search terms

```javascript
    _resetDataset() {
        this.set('dataset', new Dataset({
            pageSize: 25,
            loadHorizon: 2,
            unloadHorizon: Infinity,
            fetch: this.fetchChats.bind(this),
            observe: (datasetState) => {
                this.set('datasetState', datasetState);
            }
        }));
    },
```
template:

```hbs
        {{#search-pane
           resultSuggestion=chatSearchResultSuggestion
           isDisplaying=isSearchSelected
           searchPlaceholder=(t 'chat.chatSearch.searchPlaceholder')
           searchHelp=(t 'chat.chatSearch.searchHelp')
           performSearch=(action "searchChats")
           loadItem=(action "loadHistoricChat")
           clearSearch=(action "clearChatSearch")
        }}

            {{#impagination-dataset
               fetch=fetchChats
               dataset=dataset
               datasetState=datasetState
               page-size=25
               as |records|
            }}
                {{log "rendering results"}}
                {{log records.length}}
                {{#ember-collection
                   items=records
                   cell-layout=(fixed-grid-layout 800 80)
                   as |record|
                }}
                    {{log "rendering result"}}
                    {{log record}}
                    {{chat-search-result
                      result=record
                      loadItem="loadItem"
                      selectedResult=selectedResult
                    }}
                {{/ember-collection}}
            {{/impagination-dataset}}

        {{/search-pane}}
```

**Comment by cowboyd** [comment]
Hi Todd,

The short answer is that 1) you're spot on. Being able to clear, reload and filter results are all features that we've encountered and have had to employ workarounds.

As for 2), believe it or not, the fact that there are records immediately available before the promise resolves is a feature. They'll have the `isPending` property set to `true` and as you mentioned the content will be undefined. If you only want to render records where `isFulfilled` is true then you can guard for that with an if block. 

The pending state isntherenin case you want to show some pending content like a spinner.

**Comment by cowboyd** [comment]
I should add that we're very interested in seeing an official solution to reset() make it to master

**Comment by toddjordan** [comment]
I don't mind the records being immediately undefined while waiting, but I've been thus far unable to get it to rerender when the promise is fulfilled.

**Comment by zkwentz** [comment]
If I could weigh in, working on this myself at the moment.

Fetch expects a `thennable` object to be returned:

*forgive coffeescript*

```
new Ember.RSVP.Promise (resolve) =>
  @get('store').query('post',params).then (posts) =>
    stats.totalPages = posts.get('meta.total_pages')
    resolve(posts)
```

**Comment by toddjordan** [comment]
ok...  then the promise that query returns is not `thennable`?

**Comment by zkwentz** [comment]
It is thennable, but you're doing something with it, so what you're returning is a thennable object right, and the stuff you do `then` is just forgotten, you need to resolve in your own promise, after you've mapped your records, and set stats, etc.

**Comment by toddjordan** [comment]
ok, I'll give that a try.  Thx

**Comment by zkwentz** [comment]
Cool, minor update to my previous snippet (`resolve(posts.get('content'))`)

**Comment by zkwentz** [comment]
To be clear, I haven't got this to work either, but this gets me around the issue where it was giving my dataset an 'UnresolvedPage', to a 'ResolvedPage' with the data populated.

It would seem the data coming back from `impagination-dataset's` block isn't bound?

**Comment by zkwentz** [comment]
Okay, got it working, so basically doing the map like in your previous, `searchResults.get('content').mapBy('record')` doesn't work because these are not wrapped in an `ObjectProxy` that will fulfill.

Luckily, ember data has a nice little operator that we can add on called `toArray()` which maintains the binding.

so following on both of our examples, your updated fetch would look like this:

```javascript
fetchChats(pageOffset, pageSize, stats) {
        console.log('fetch');
        return this.get('store').query('chat-search-result', {
            query: this.get('chatSearchResultSuggestion.searchValue'),
            expand: 'to,from',
            targetJids: [this.get('activeRoom.jid')],
            pageSize: pageSize,
            pageNumber: pageOffset,
            order: 'recent'
        }).then((searchResults) => {
            console.log('then');
            const results = searchResults.toArray();
            this.set('chatSearchResultSuggestion', ResultSuggestion.create({
                results: results,
                metaData: { total: searchResults.get('meta.total') },
                searchValue: this.get('chatSearchValue')
            }));
            stats.totalPages = searchResults.get('meta.total');
            console.log(`results of then`);
            console.dir(results);
            return new Ember.RSVP.Promise((resolve)=>
              resolve(results);
            );
        });
    },
```

**Comment by toddjordan** [comment]
Awesome!  Lemme try.  Thanks for the time :-)

**Comment by zkwentz** [comment]
Sure thing your code helped me get going, I was pretty confused before. :+1:

**Comment by cowboyd** [comment]
Hmmm... You shouldn't have to wrap the search results in a promise at the end there. If results is an array, then returning it will make the top level promise resolve to that.

Also we should probably make clear in the read me that `fetch` expects the collection yielded by the thennable to be immutable, hence the need for `toArray`

Sorry for the confusion

**Comment by toddjordan** [comment]
Still unable to get the ember-collection component to rerender when the dataset is fullfilled.  I'm now using toArray. 

```javascript
    fetchChats(pageOffset, pageSize, stats) {
        console.log('fetch');
        return this.get('store').query('chat-search-result', {
            query: this.get('chatSearchResultSuggestion.searchValue'),
            expand: 'to,from',
            targetJids: [this.get('activeRoom.jid')],
            pageSize: pageSize,
            pageNumber: pageOffset,
            order: 'recent'
        }).then((searchResults) => {
            console.log('then');
            const results = searchResults.toArray();
            this.set('chatSearchResultSuggestion', ResultSuggestion.create({
                results: results,
                metaData: { total: searchResults.get('meta.total') },
                searchValue: this.get('chatSearchValue')
            }));
            stats.totalPages = searchResults.get('meta.total');
            console.log(`results of then`);
            console.dir(results);
            return results;
        });
    },
```

**Comment by toddjordan** [comment]
stepping through the whole flow with debugger.  Will post if I find anything interesting.

**Comment by toddjordan** [comment]
After stepping through down to impagination, it looks like the promise gets successfully resolved and impagination's then on the fetch gets successfully executed.  Looks happy path.  When I inspect the dataset object from the browser I can get references to the resolved items.  But still not rerender happening...
![image](https://cloud.githubusercontent.com/assets/3609063/12066764/47a1b4ce-afbb-11e5-9af7-6265c66bc0be.png)

At the top level, the dataset looks as follows.  I don't know if that's right or not...
![image](https://cloud.githubusercontent.com/assets/3609063/12066795/a8898230-afbb-11e5-9a7c-921abe04ff44.png)

**Comment by cowboyd** [comment]
I'm Mobile at the moment so it's hard to help you debug, but if you're instantiating your dataset by yourself, are you also observing it so that every time it emits a new state you can re-render?

**Comment by zkwentz** [comment]
For my working example, this is my template:

```handlebars
{{#each posts as |post|}}
  {{#if post.content}}
    {{ug-post model=post.content}}
  {{/if}}
{{/each}}
```

**Comment by toddjordan** [comment]
I was able to get the dataset component to re-render by setting the dataset in the observe dataset function after render so that it would hit the didReceiveAttrs hook of the dataset component, but I'm still unable to get my ember-collection to do likewise.  I'll try switching to each to see if its an issue with the ember-collection component, but I was under the impression the each would have rendering consequences for large datasets.

```javascript
    _resetDataset() {
        this.set('dataset', new Dataset({
            pageSize: 25,
            loadHorizon: 2,
            unloadHorizon: Infinity,
            fetch: this.fetchChats.bind(this),
            observe: (datasetState) => {
                Ember.run.scheduleOnce('afterRender', () => {
                    this.set('datasetState', datasetState);
                });
            }
        }));
    },
```

**Comment by toddjordan** [comment]
So with {{#each}} it will load the first page for me, but no additional pages.  I'm assuming that's because {{#each}} isn't set up for virtual scrolling, and I would have to add the scroll event handling code.  So there's something different about ember-collection where its not handling the changes in the record collection. Next I can try virtual-each, which I believe is in the impagination demo, and see if I can get that to render.

**Comment by toddjordan** [comment]
virtual-each does in fact render, but I'm getting in some kind of infinite fetch render loop 😢I feel like most of my problems are because I'm implementing the resetting of dataset which the addon's not currently set up for or tested with, so I'm going to throw in the towel on this.  I might pull down the source and try to add the feature internally and see how far that gets me.  If anything this has all been an education on component rendering :-P

**Comment by fivetanley** [comment]
In `_resetDataset` do you need to tear down the observer for the old dataset?

**Comment by toddjordan** [comment]
Just a quick update...  Got rendering/infinite scroll working with ember smoke-and-mirrors.  I am considering incorporating ember-impagination as well to handle the fetching/unfetching of data.  Will probably spend more time on in in the next few weeks.  Its up to you guys whether you want to keep this issue open around the reset functionality or close it and track it elsewhere.

Thanks so much for the ideas and help thus far!

**Comment by cowboyd** [comment]
@toddjordan We definitely want to keep this open so that we can modify `ember-impagination` to fit this use-case. Quick question. If the component yielded an action to reset itself, would that work for you? e.g.

```hbs
{{#impagination-dataset as |dataset|}}
  <button on-click={{dataset.reset}}>Reset!</button>
  <button on-click={{dataset.reload}}>Reload!</button>
{{/impagination-dataset}}
```hbs

**Comment by toddjordan** [comment]
Possibly.  So in this case I'd have to wrap my search-pane component with impagination as follows...

```javascript
{{#impagination-dataset fetch=myFetch as |dataset|}}
  {{#search-pane resetAction=(dataset.reset) searchAction=(action "performSearch")}}
      {{#ember-collection items=dataset as |record|}}
        {{chat-search-result result=record}}
      {{/ember-collection}}
  {{search-pane}}
{{/impagination-dataset}}
```

The odd thing is I need to re-fetch based on the query given in search pane, but at the same time, I need the search pane to invoke reset when when a new term is entered.  It seems like a circular dependency, but I guess the search-pane could send an action (performSearch) up with the search query text as an argument to the parent component or route of the dataset, which would also implement the fetch function.

**Comment by cowboyd** [comment]
In that case could you not have the `performSearch` change the value of the `myFetch` which _should_ have the effect of reseting the dataset (if it doesn't then that's definitely a bug).

**Comment by cowboyd** [comment]
That is to say, that the `myFetch` property is a function which closes over a set of bound search parameters: new search params recomputes new fetch function, recomputes new dataset.

**Comment by toddjordan** [comment]
Maybe I'm not understanding.  I thought I would need to somehow provide the search query string collected by the search pane to the fetch function. in the parent component.  That's essentially what perform search was doing: passing the new query information up to where the fetch function could access it.

**Comment by toddjordan** [comment]
I guess it would be a possible use of the mut helper, so instead of passing up an action I can just have the parent component own the query data.

**Comment by cowboyd** [comment]
I don't think you need to use the `mut` helper if the data is coming down from the parent component. Basically, the `performSearch` action would set a new fetch function which would come down again to the `impagination-dataset`.

Another option would be to have your search pane yield a fetch function which is then passed to the dataset.

**Comment by toddjordan** [comment]
ok, I see what you are saying.  `performSearch` would actually pass the fetch function up to the parent, in theory causing fetch to recalculate.  I think if I remember looking at the impagination component source, that the dataset was only created on init.  My memory may not be right though...

Also, in my case its a bit trickier, as the search-pane is reusable component that can search various entities within my app (doesn't really care what its searching, just provides a way to provide search criteria and yields to iterate results.  Today the performSearch closure action on the parent already knows whether its a person  or a chat search for instance and knows how to fetch appropriately.  That's why I was saying all the `performSearch` function really just needs to pass is the query data.

**Comment by toddjordan** [comment]
ok, you're right, dataset resets when fetch changes.

**Comment by cowboyd** [comment]
I think that the search pane can still just pass query data to its action. The fetch function would be computed in your controller or route, but it would have the query data as a dependency.

**Comment by flexyford** [comment]
I want to start working on a PR to introduce a number of functions that exist on the `dataset`
[ ] refresh() - refreshes the dataset at the current read-offset
[ ] reset() - resets the dataset to read-offset 0
[ ] setReadOffset(offset) - sets the read-offset to `offset`

```hbs
{{#search-pane searchAction=(action "performSearch")}}
  {{#impagination-dataset fetch=myFetch on-dataset=(action "observeDataset") as |dataset|}}
      {{#ember-collection items=dataset as |record|}}
        {{chat-search-result result=record}}
      {{/ember-collection}}
  {{/impagination-dataset}}
{{/search-pane}}

```

``` javascript
   _refreshDataset() {
        this.get('dataset').refreshDataset()
    },
    observeDataset: function(dataset) {
        this.set('dataset', dataset)
    }
```

Thoughts?

**Comment by toddjordan** [comment]
@cowboyd agreed, you certainly could.  It doesn't seem super intuitive but I definitely see that working

@flexyford I like that.  It keeps true to how I originally thought how the template should be layed out.

**Comment by toddjordan** [comment]
@flexyford @cowboyd  If you don't want to give the parent the actual dataset object and stay more "data-down", you can can expose an action called `reset` with a reset function as an argument.  That way, the parent component can just call reset when it changes a query or some other context that would cause the dataset to be reset.

Not sure if I like it better or not, but another option...

```hbs
{{#search-pane searchAction=(action "performSearch")}}
  {{#impagination-dataset fetch=myFetch provideRefresh=(action "provideDatasetRefresh") as |dataset|}}
      {{#ember-collection items=dataset as |record|}}
        {{chat-search-result result=record}}
      {{/ember-collection}}
  {{/impagination-dataset}}
{{/search-pane}}
```
```javascript
_refreshDataset() {
  this.get('refreshData')();
},
actions: {
  provideDatasetRefresh(refreshFn) {
    this.set('refreshData', refreshFn);
  }
}
```

**Comment by flexyford** [comment]
@toddjordan Passing the entire dataset up does not entirely adhere to the DDAU principle. However, I really like the fact that these actions are available in the controller/route, AS WELL AS in a child component utilizing a similar syntax.

```hbs
{{#search-pane searchAction=(action "performSearch")}}
  {{#impagination-dataset on-dataset=(action "observeDataset") fetch=myFetch as |dataset|}}
      {{#ember-collection items=dataset as |record|}}
        {{chat-search-result result=record on-no-results=(action dataset.refresh}}
      {{/ember-collection}}
  {{/impagination-dataset}}
{{/search-pane}}
```

Thanks for bringing up this point. I'll give it some additional consideration.

**Comment by seanrucker** [comment]
I've run into the need to get the dataset to refresh as well. Here's how I got it working. 

```javascript
// controllers/foo.js

import Ember from 'ember';

export default Ember.Controller.extend({

    store: Ember.inject.service(),

    query: null,

    actions: {

        fetch(query, pageNumber, pageSize, stats) {

            let params = {
                query: query
            };

            return this.get('store').query('foo', params).then((result) => {
                let meta = result.get('meta');
                stats.totalPages = meta.totalPages;
                return result.toArray();
            });
        }
    }
});
```

```handlebars
{{!-- templates/foo.hbs --}}

{{input value=query}}
{{#impagination-dataset fetch=(action "fetch" query)}}
```

With this approach, each time the value of `query` changes the fetch action is called again, the value of query is passed into the function, and the data refreshes. 

Thoughts?

**Comment by flexyford** [comment]
@seanrucker This is a brilliant approach when we want to refresh the data based on queryParams. And if that is your use-case for refreshing, then I highly recommend it! I will add this to the README!

I'm still considering alternative to enable `filter`ing records on the front-end. If we want `ember-impagination` to handle filtering for us, then the value of `query` will not change, so we need a different way to refresh data such that filtering is applied to the latest dataset.

**Comment by flexyford** [comment]
Added way to reset, reload, and refilter dataset in `0.2.0`

**Comment by toddjordan** [comment]
Thanks!
