### ISSUE TITLE
You modified records.length twice in a single render

### ISSUE THREAD

**Issue by seanrucker** [thefrontside/ember-impagination#38]
If I include this line (as per the example):

`<div class="records">Total Records: {{records.length}}</div>` 

I get an error in the console:

`DEPRECATION: You modified records.length twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0 [deprecation id: ember-views.render-double-modify]`

**Comment by seanrucker** [comment]
This also happens if I try `{{log records}}` inside the impagination-dataset component.

**Comment by flexyford** [comment]
This has been fixed in the `v.1.0.0` milestone
