### ISSUE TITLE
Move `Array` polyfills to main plugin?

### ISSUE THREAD

**Issue by sarenji** [thefrontside/ember-impagination#47]
I believe the `Array.prototype.fill` and `Array.from` methods are ES6-only methods, which `ember-impagination` uses. While using `ember-impagination` in another app, I'm getting errors in my own tests related to these methods not being defined in `phantomjs`. I took a look and found out that this plugin polyfills those methods, but in a [`test-helper`](https://github.com/thefrontside/ember-impagination/blob/04852354bc5f0c1f193ae9ed5f9124877e8cc056/tests/test-helper.js). Since they're polyfilled in the test environment only, the plugin doesn't get the benefit of ES5 support.

What do y'all think about moving those polyfills into the main plugin so that we have ES5 support out of the box? It would also avoid forcing people who use this plugin to polyfill again for `phantomjs`.

**Comment by flexyford** [comment]
Array.prototype pollyfills are removed in version `0.2.0`
