### ISSUE TITLE
Clean up pages interface

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/ember-impagination#6]

**Comment by Robdel12** [comment]
What does this mean?

**Comment by flexyford** [comment]
You bet we cleaned up these pages interfaces. [Impagination proper upgrade](https://github.com/flexyford/impagination/releases/tag/1.0.0-alpha.3) took care of that. See this [commit](https://github.com/flexyford/impagination/blob/master/src/state.js) where our pages-interface is now `state`
