### ISSUE TITLE
Performance (setting totalPages to a high number)

### ISSUE THREAD

**Issue by graup** [thefrontside/ember-impagination#68]
I had some bug that crashed my app when I assigned `stats.totalPages` to a big value. Removing that line solved the problem, so I was wondering if that is needed somewhere in the component? I searched the repo but the variable doesn't seem to be used anywhere. If that's the case, what is the need for the `stats` variable anyhow?

**Comment by graup** [comment]
I think I just answered my own question, that variable is used in the underlying Impagination lib (https://github.com/flexyford/impagination/blob/4ff6f2f016860d6c528f31cbd8cd7cc58142f725/src/dataset.js#L121)

So I should figure out why assigning it to 256 crashed my browser.

**Comment by graup** [comment]
Something is weird here. The higher the number of totalPages, the longer the browser is busy. Can anyone else replicate that?

**Comment by flexyford** [comment]
@graup you are correct. `totalPages` is used by the underlying `impagination` library. Setting the `totalPages` variable will initialize the entire `pages` array with `Unrequested Pages`, such that `pages.length; //=> totalPages`. That means each `Unrequested Page` has `#pageSize` records, which are initialized as `null`. 

When returning `totalPages`, then `record.length; //=> totalPages * pageSize`, which may not be the desired result for a large set of `totalPages`.

**Comment by graup** [comment]
Thanks for the reply. Do you have an idea how to improve this? I thought the advantage of Impagination is that it doesn't keep all records in memory, so unfetched pages shouldn't have an impact on performance.

Maybe I could just set `totalPages` to a small number at first and keep increasing it later when the user gets close to the end.

**Comment by cowboyd** [comment]
@graup that would be a workaround, however the long term solution is to make a `PageStore` object to lazily fetch pages, in the same way that the dataset lazily fetches the records.

**Comment by graup** [comment]
I see. Should I open an issue on the Impagination repo? If you could point me to where you would implement that I can also try to contribute a solution.

**Comment by flexyford** [comment]
Hey @graup, thanks for your notes and input. 

We're working on `impagination 1.0.0` and your issues / suggestion is making it into our next release. We are only in the beginning stages, but you can check the progress at this [Impagination Pull Request](https://github.com/flexyford/impagination/pull/35). Please check back for documentation in the coming weeks. Just wanted to let you know we're working on it :)

**Comment by graup** [comment]
Thanks for the update, @flexyford! I'm using ember-impagination in a deployed app, will be happy to test the next version.

**Comment by flexyford** [comment]
Just getting back to this Issue: We have released `impagination 1.0.0-alpha.x` and are lazy loading pages when setting total Pages. [Therefore the length is calculated without eagerly loading the pages.](https://github.com/flexyford/impagination/blob/063561f2e3ba76cbed64522eb785004292047e27/src/lazy-store.js#L150-L155)
