### ISSUE TITLE
Read dataset without updating readOffset

### ISSUE THREAD

**Issue by TopsyCM** [thefrontside/ember-impagination#77]
Is it possible to read data from the impagination-dataset without updating the readOffset? Currently the two appear to be coupled. From [impagination-dataset.js](https://github.com/thefrontside/ember-impagination/blob/master/addon/components/impagination-dataset.js):

``` javascript
objectAt(i) {
    let record = this.datasetState.get(i);
    Ember.run.debounce(this, 'objectReadAt', i, 1, true);
    return record;
 },
```

This is fine if all you are doing is displaying the dataset. However, if you need to do anything else with the dataset, then each read updates the readOffset which updates the dataset which can lead to circular calls. Is it possible to separate these two operations completely?

**Comment by cowboyd** [comment]
@TopsyCM Yes, this is actually in the plans to completely remove this coupling since it violates DDAU. We haven't decide whether to make the legacy behavior opt-in, or just completely remove it.

**Comment by TopsyCM** [comment]
Super! I am looking forward to it. Now I just need to get things working reliably until that lands.

**Comment by sarenji** [comment]
This just burned me, too —not entirely sure why, but after I called `setReadOffset` (via an action or other ways) there would be two states output, one for the next page and one for the old page, so `dataset.readOffset` always read as `0` in the end. That meant no matter how many times I pressed a "next" button I'd be getting the 2nd page. When I removed the offending line, everything worked.

Do you know the historical reason why the two were coupled? Knowing the reason would help determine the right path. If there's anything depending on that coupled functionality, then for backwards-compatibility, it could be opt-in/out. Maybe via `config/environment.js`?

**Comment by Robdel12** [comment]
@flexyford I know you've been doing a lot of work on this library lately. Do you have any thoughts on this?

**Comment by cowboyd** [comment]
@sarenji The historical reason was to have it work "out of the box" with `ember-collection`, `virtual-each` and friends, kind of like the asynchronous relationships in Ember Data. 

@flexyford Is currently working on Impagination 2.0 which will address this issue. Perhaps we could have a patch release that provides an option to turn this off.

**Comment by cowboyd** [comment]
@TopsyCM @sarenji `setReadOffset` has now been completely decoupled from reads and must always be explicitly called.

In other words, reads are pure and side-effect free :)

**Comment by TopsyCM** [comment]
I'm looking forward to trying it out. However, I don't see any tags or releases in github. The changelog doesn't seem to have any info on the 1.0.0-alpha.x npm releases. I probably missed a discussion about this somewhere.
